language: r
warnings_are_errors: true
sudo: required
cache: packages
dist: trusty

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev

r_github_packages:
    - jimhester/covr

after_success:
    - Rscript -e 'covr::codecov()'
